tasks:
  - name: Terminal 1
    init: |
      sudo apt-get update
      sudo apt install -y mysql-client-core-8.0 python3-pymysql
      python -m pip install --upgrade pip 
      pip install mysqlclient django-crispy-forms django Pillow
